# 1. Objects to build (Main Folder)
# We list the local .o files and tell the system to enter subfolders
obj-y := allowlist.o apk_sign.o app_profile.o extras.o \
         feature.o file_wrapper.o kernel_compat.o kernel_umount.o \
         ksud.o lsm_hooks.o seccomp_cache.o setuid_hook.o \
         su_mount_ns.o sucompat.o supercalls.o throne_tracker.o \
         util.o

# 2. Tell the system to go into subfolders
obj-y += kernel/
obj-y += selinux/

# These lines ensure Kbuild actually enters the directories to find ksu.o and rules.o
subdir-y += kernel
subdir-y += selinux

# 3. Include Paths & Flags
# $(src) points to drivers/kernelsu, $(srctree) is the root of the kernel
ccflags-y += -I$(srctree)/security/selinux/include
ccflags-y += -I$(srctree)/$(src)/selinux
ccflags-y += -I$(srctree)/$(src)
ccflags-y += -I$(src)/kernel
ccflags-y += -DCONFIG_SECURITY_SELINUX_SIDTAB_HASH_BITS=9

# Critical Flags for KSU_NEXT
ccflags-y += -DCONFIG_KSU_NEXT_MANUAL_HOOK
ccflags-y += -Wno-strict-prototypes -Wno-implicit-function-declaration

# 4. THE V2 SIGNATURE (The Handshake)
KSU_EXPECTED_SIZE := 0x3e6
KSU_EXPECTED_HASH := 79e590113c4c4c0c222978e413a5faa801666957b1212a328e46c00c69821bf7

ccflags-y += -DKSU_NEXT_EXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
ccflags-y += -DKSU_NEXT_EXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"
